spring:
  cloud:
    nacos:
#      config:
#        server-addr: 127.0.0.1:8848
#        file-extension: yml
      discovery:
        server-addr: 127.0.0.1:8848
        auto-register: true
    gateway:
#      discovery:
#        locator:
#          enabled: true
#          lowerCaseServiceId: true
      routes:
        - id: busine
          uri: http://localhost:9002/config/get
          predicates:
            - Path=/config/get
